import type { College } from "@/types/college";


export const sampleColleges: College[] = [
  {
    id: 101,
    name: "Pillai College of Engineering",
    short_form: "NIT",
    normalized_name: "national_institute_of_technology",
    admin_name: "Dr. Rajesh Kumar",
    address: "123 Main Street",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    affiliation: "Autonomous",
    email: "contact@nit.edu",
    email_verified: true,
    phone: "+91-9876543210",
    phone_verified: true,
    password_hash: "hashed_password_1",
    logoUrl: "/clubs/csi.png",
    username: "nitadmin",
    website_url: "https://www.nit.edu",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: 1,
  },
  {
    id: 102,
    name: "Indian Institute of Science",
    short_form: "IISc",
    normalized_name: "indian_institute_of_science",
    admin_name: "Dr. Priya Sharma",
    address: "456 Science Road",
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    affiliation: "Autonomous",
    email: "contact@iisc.ac.in",
    email_verified: true,
    phone: "+91-9123456780",
    phone_verified: true,
    password_hash: "hashed_password_2",
    logoUrl: "https://via.placeholder.com/100x100.png?text=IISc",
    username: "iiscadmin",
    website_url: "https://www.iisc.ac.in",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: 2,
  },
];
